
/*-
 * ============LICENSE_START==========================================
 * OPENECOMP - DCAE
 * ===================================================================
 * Copyright (c) 2017 AT&T Intellectual Property. All rights reserved.
 * ===================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0 
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END============================================
 */
	
// Autogenerated
// Do not edit. No need to extend this class.
package org.openecomp.dcae.controller.service.common.docker.servers.service;





import java.io.InputStream;

import org.openecomp.ncomp.sirius.manager.IRequestHandler;
import org.openecomp.ncomp.sirius.manager.ISwaggerHandler;
import org.openecomp.ncomp.sirius.manager.ISiriusPlugin;
import org.openecomp.ncomp.sirius.manager.ISiriusServer;
import org.openecomp.ncomp.sirius.manager.ISiriusProvider;
import org.openecomp.ncomp.sirius.manager.ManagementServer;
import org.openecomp.ncomp.sirius.manager.SwaggerUtils;
import org.openecomp.ncomp.sirius.function.FunctionUtils;
import org.openecomp.ncomp.component.ApiRequestStatus;

import org.apache.log4j.Logger;

import org.openecomp.ncomp.sirius.manager.logging.NcompLogger;
import org.openecomp.logger.StatusCodeEnum;
import org.openecomp.logger.EcompException;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.json.JSONObject;

import java.util.Date;

import org.openecomp.dcae.controller.service.common.docker.servers.service.logging.CommonDockerServiceOperationEnum;
import org.openecomp.dcae.controller.service.common.docker.servers.service.logging.CommonDockerServiceMessageEnum;




import org.openecomp.dcae.controller.service.common.docker.service.impl.CommonDockerServiceImpl;



public class DcaeCommonDockerService extends CommonDockerServiceImpl implements ISiriusProvider, ISiriusPlugin {
	public static final Logger logger = Logger.getLogger(DcaeCommonDockerService.class);
	static final NcompLogger ecomplogger = NcompLogger.getNcompLogger();
	public DcaeCommonDockerServiceProvider controller;
	ISiriusServer server;

	public DcaeCommonDockerService(ISiriusServer server) {
		this.server = server;
		this.controller = new DcaeCommonDockerServiceProvider(server,this);
	}

	public void deploy(java.lang.String instanceName, java.lang.String containerPath) {
		
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "deploy", ApiRequestStatus.START, duration_,instanceName,containerPath);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CommonDockerServiceOperationEnum.CommonDockerService_deploy,server,this);
		ecomplogger.recordMetricEventStart(CommonDockerServiceOperationEnum.CommonDockerService_deploy,"self:" + ManagementServer.object2ref(this));
		try {
			 controller.deploy(instanceName,containerPath);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "deploy", ApiRequestStatus.ERROR, duration_,instanceName,containerPath);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CommonDockerServiceMessageEnum.REQUEST_FAILED_deploy, e.toString());
			EcompException e1 =  EcompException.create(CommonDockerServiceMessageEnum.REQUEST_FAILED_deploy,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CommonDockerServiceMessageEnum.REQUEST_FAILED_deploy, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "deploy", ApiRequestStatus.OKAY, duration_,instanceName,containerPath);
		
	}

	public void undeploy(java.lang.String instanceName) {
		
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "undeploy", ApiRequestStatus.START, duration_,instanceName);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CommonDockerServiceOperationEnum.CommonDockerService_undeploy,server,this);
		ecomplogger.recordMetricEventStart(CommonDockerServiceOperationEnum.CommonDockerService_undeploy,"self:" + ManagementServer.object2ref(this));
		try {
			 controller.undeploy(instanceName);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "undeploy", ApiRequestStatus.ERROR, duration_,instanceName);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CommonDockerServiceMessageEnum.REQUEST_FAILED_undeploy, e.toString());
			EcompException e1 =  EcompException.create(CommonDockerServiceMessageEnum.REQUEST_FAILED_undeploy,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CommonDockerServiceMessageEnum.REQUEST_FAILED_undeploy, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "undeploy", ApiRequestStatus.OKAY, duration_,instanceName);
		
	}

	public org.openecomp.dcae.controller.core.service.HealthTestResponse test(java.lang.String instanceName) {
		org.openecomp.dcae.controller.core.service.HealthTestResponse res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "test", ApiRequestStatus.START, duration_,instanceName);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CommonDockerServiceOperationEnum.CommonDockerService_test,server,this);
		ecomplogger.recordMetricEventStart(CommonDockerServiceOperationEnum.CommonDockerService_test,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.test(instanceName);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "test", ApiRequestStatus.ERROR, duration_,instanceName);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CommonDockerServiceMessageEnum.REQUEST_FAILED_test, e.toString());
			EcompException e1 =  EcompException.create(CommonDockerServiceMessageEnum.REQUEST_FAILED_test,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CommonDockerServiceMessageEnum.REQUEST_FAILED_test, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "test", ApiRequestStatus.OKAY, duration_,instanceName);
		return res;
	}

	public void suspend(java.lang.String instanceName) {
		
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "suspend", ApiRequestStatus.START, duration_,instanceName);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CommonDockerServiceOperationEnum.CommonDockerService_suspend,server,this);
		ecomplogger.recordMetricEventStart(CommonDockerServiceOperationEnum.CommonDockerService_suspend,"self:" + ManagementServer.object2ref(this));
		try {
			 controller.suspend(instanceName);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "suspend", ApiRequestStatus.ERROR, duration_,instanceName);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CommonDockerServiceMessageEnum.REQUEST_FAILED_suspend, e.toString());
			EcompException e1 =  EcompException.create(CommonDockerServiceMessageEnum.REQUEST_FAILED_suspend,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CommonDockerServiceMessageEnum.REQUEST_FAILED_suspend, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "suspend", ApiRequestStatus.OKAY, duration_,instanceName);
		
	}

	public void resume(java.lang.String instanceName) {
		
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "resume", ApiRequestStatus.START, duration_,instanceName);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CommonDockerServiceOperationEnum.CommonDockerService_resume,server,this);
		ecomplogger.recordMetricEventStart(CommonDockerServiceOperationEnum.CommonDockerService_resume,"self:" + ManagementServer.object2ref(this));
		try {
			 controller.resume(instanceName);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "resume", ApiRequestStatus.ERROR, duration_,instanceName);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CommonDockerServiceMessageEnum.REQUEST_FAILED_resume, e.toString());
			EcompException e1 =  EcompException.create(CommonDockerServiceMessageEnum.REQUEST_FAILED_resume,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CommonDockerServiceMessageEnum.REQUEST_FAILED_resume, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "resume", ApiRequestStatus.OKAY, duration_,instanceName);
		
	}

	public void pushManagerConfiguration(java.lang.String instanceName) {
		
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "pushManagerConfiguration", ApiRequestStatus.START, duration_,instanceName);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CommonDockerServiceOperationEnum.CommonDockerService_pushManagerConfiguration,server,this);
		ecomplogger.recordMetricEventStart(CommonDockerServiceOperationEnum.CommonDockerService_pushManagerConfiguration,"self:" + ManagementServer.object2ref(this));
		try {
			 controller.pushManagerConfiguration(instanceName);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "pushManagerConfiguration", ApiRequestStatus.ERROR, duration_,instanceName);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CommonDockerServiceMessageEnum.REQUEST_FAILED_pushManagerConfiguration, e.toString());
			EcompException e1 =  EcompException.create(CommonDockerServiceMessageEnum.REQUEST_FAILED_pushManagerConfiguration,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CommonDockerServiceMessageEnum.REQUEST_FAILED_pushManagerConfiguration, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "pushManagerConfiguration", ApiRequestStatus.OKAY, duration_,instanceName);
		
	}

	public void pollManagerConfiguration(java.lang.String instanceName) {
		
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "pollManagerConfiguration", ApiRequestStatus.START, duration_,instanceName);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CommonDockerServiceOperationEnum.CommonDockerService_pollManagerConfiguration,server,this);
		ecomplogger.recordMetricEventStart(CommonDockerServiceOperationEnum.CommonDockerService_pollManagerConfiguration,"self:" + ManagementServer.object2ref(this));
		try {
			 controller.pollManagerConfiguration(instanceName);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "pollManagerConfiguration", ApiRequestStatus.ERROR, duration_,instanceName);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CommonDockerServiceMessageEnum.REQUEST_FAILED_pollManagerConfiguration, e.toString());
			EcompException e1 =  EcompException.create(CommonDockerServiceMessageEnum.REQUEST_FAILED_pollManagerConfiguration,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CommonDockerServiceMessageEnum.REQUEST_FAILED_pollManagerConfiguration, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "pollManagerConfiguration", ApiRequestStatus.OKAY, duration_,instanceName);
		
	}

	public org.eclipse.emf.ecore.EObject managerConfiguration(java.lang.String instanceName) {
		org.eclipse.emf.ecore.EObject res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "managerConfiguration", ApiRequestStatus.START, duration_,instanceName);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CommonDockerServiceOperationEnum.CommonDockerService_managerConfiguration,server,this);
		ecomplogger.recordMetricEventStart(CommonDockerServiceOperationEnum.CommonDockerService_managerConfiguration,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.managerConfiguration(instanceName);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "managerConfiguration", ApiRequestStatus.ERROR, duration_,instanceName);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CommonDockerServiceMessageEnum.REQUEST_FAILED_managerConfiguration, e.toString());
			EcompException e1 =  EcompException.create(CommonDockerServiceMessageEnum.REQUEST_FAILED_managerConfiguration,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CommonDockerServiceMessageEnum.REQUEST_FAILED_managerConfiguration, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "managerConfiguration", ApiRequestStatus.OKAY, duration_,instanceName);
		return res;
	}

	public org.json.JSONObject managerOperation(java.lang.String instanceName, java.lang.String operation, org.json.JSONObject parameters) {
		org.json.JSONObject res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "managerOperation", ApiRequestStatus.START, duration_,instanceName,operation,parameters);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CommonDockerServiceOperationEnum.CommonDockerService_managerOperation,server,this);
		ecomplogger.recordMetricEventStart(CommonDockerServiceOperationEnum.CommonDockerService_managerOperation,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.managerOperation(instanceName,operation,parameters);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "managerOperation", ApiRequestStatus.ERROR, duration_,instanceName,operation,parameters);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CommonDockerServiceMessageEnum.REQUEST_FAILED_managerOperation, e.toString());
			EcompException e1 =  EcompException.create(CommonDockerServiceMessageEnum.REQUEST_FAILED_managerOperation,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CommonDockerServiceMessageEnum.REQUEST_FAILED_managerOperation, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "managerOperation", ApiRequestStatus.OKAY, duration_,instanceName,operation,parameters);
		return res;
	}

	public void updateConfigurationFromPolicy(java.lang.String instanceName) {
		
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "updateConfigurationFromPolicy", ApiRequestStatus.START, duration_,instanceName);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CommonDockerServiceOperationEnum.CommonDockerService_updateConfigurationFromPolicy,server,this);
		ecomplogger.recordMetricEventStart(CommonDockerServiceOperationEnum.CommonDockerService_updateConfigurationFromPolicy,"self:" + ManagementServer.object2ref(this));
		try {
			 controller.updateConfigurationFromPolicy(instanceName);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "updateConfigurationFromPolicy", ApiRequestStatus.ERROR, duration_,instanceName);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CommonDockerServiceMessageEnum.REQUEST_FAILED_updateConfigurationFromPolicy, e.toString());
			EcompException e1 =  EcompException.create(CommonDockerServiceMessageEnum.REQUEST_FAILED_updateConfigurationFromPolicy,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CommonDockerServiceMessageEnum.REQUEST_FAILED_updateConfigurationFromPolicy, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "updateConfigurationFromPolicy", ApiRequestStatus.OKAY, duration_,instanceName);
		
	}

	public void runHealthTests() {
		
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "runHealthTests", ApiRequestStatus.START, duration_);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CommonDockerServiceOperationEnum.CommonDockerService_runHealthTests,server,this);
		ecomplogger.recordMetricEventStart(CommonDockerServiceOperationEnum.CommonDockerService_runHealthTests,"self:" + ManagementServer.object2ref(this));
		try {
			 controller.runHealthTests();
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "runHealthTests", ApiRequestStatus.ERROR, duration_);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CommonDockerServiceMessageEnum.REQUEST_FAILED_runHealthTests, e.toString());
			EcompException e1 =  EcompException.create(CommonDockerServiceMessageEnum.REQUEST_FAILED_runHealthTests,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CommonDockerServiceMessageEnum.REQUEST_FAILED_runHealthTests, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "runHealthTests", ApiRequestStatus.OKAY, duration_);
		
	}








	@Override
	public void start() {
		controller.start();
	}

	public static void ecoreSetup() {
		DcaeCommonDockerServiceProvider.ecoreSetup();
	}
	public DcaeCommonDockerServiceProvider getSiriusProvider() {
		return controller;
	}
}
