
/*-
 * ============LICENSE_START==========================================
 * OPENECOMP - DCAE
 * ===================================================================
 * Copyright (c) 2017 AT&T Intellectual Property. All rights reserved.
 * ===================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0 
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END============================================
 */
	
// Autogenerated
// Do not edit. No need to extend this class.
package org.openecomp.dcae.controller.service.cdap.cluster.servers.manager;





import java.io.InputStream;

import org.openecomp.ncomp.sirius.manager.IRequestHandler;
import org.openecomp.ncomp.sirius.manager.ISwaggerHandler;
import org.openecomp.ncomp.sirius.manager.ISiriusPlugin;
import org.openecomp.ncomp.sirius.manager.ISiriusServer;
import org.openecomp.ncomp.sirius.manager.ISiriusProvider;
import org.openecomp.ncomp.sirius.manager.ManagementServer;
import org.openecomp.ncomp.sirius.manager.SwaggerUtils;
import org.openecomp.ncomp.sirius.function.FunctionUtils;
import org.openecomp.ncomp.component.ApiRequestStatus;

import org.apache.log4j.Logger;

import org.openecomp.ncomp.sirius.manager.logging.NcompLogger;
import org.openecomp.logger.StatusCodeEnum;
import org.openecomp.logger.EcompException;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.json.JSONObject;

import java.util.Date;

import org.openecomp.dcae.controller.service.cdap.cluster.servers.manager.logging.CdapClusterManagerOperationEnum;
import org.openecomp.dcae.controller.service.cdap.cluster.servers.manager.logging.CdapClusterManagerMessageEnum;







import java.util.Date;





import org.openecomp.ncomp.sirius.manager.server.LoggerInfo;





import org.openecomp.ncomp.sirius.manager.server.ServerFactory;


import org.openecomp.dcae.controller.service.cdap.cluster.manager.impl.CdapClusterManagerImpl;



public class DcaeCdapClusterManager extends CdapClusterManagerImpl implements ISiriusProvider {
	public static final Logger logger = Logger.getLogger(DcaeCdapClusterManager.class);
	static final NcompLogger ecomplogger = NcompLogger.getNcompLogger();
	public DcaeCdapClusterManagerProvider controller;
	ISiriusServer server;

	public DcaeCdapClusterManager(ISiriusServer server) {
		this.server = server;
		this.controller = new DcaeCdapClusterManagerProvider(server,this);
	}

	public org.openecomp.dcae.controller.core.service.HealthTestResponse test() {
		org.openecomp.dcae.controller.core.service.HealthTestResponse res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "test", ApiRequestStatus.START, duration_);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_test,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_test,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.test();
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "test", ApiRequestStatus.ERROR, duration_);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_test, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_test,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_test, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "test", ApiRequestStatus.OKAY, duration_);
		return res;
	}

	public void suspend() {
		
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "suspend", ApiRequestStatus.START, duration_);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_suspend,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_suspend,"self:" + ManagementServer.object2ref(this));
		try {
			 controller.suspend();
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "suspend", ApiRequestStatus.ERROR, duration_);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_suspend, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_suspend,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_suspend, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "suspend", ApiRequestStatus.OKAY, duration_);
		
	}

	public void resume() {
		
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "resume", ApiRequestStatus.START, duration_);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_resume,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_resume,"self:" + ManagementServer.object2ref(this));
		try {
			 controller.resume();
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "resume", ApiRequestStatus.ERROR, duration_);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_resume, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_resume,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_resume, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "resume", ApiRequestStatus.OKAY, duration_);
		
	}

	public java.lang.String publicKey() {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "publicKey", ApiRequestStatus.START, duration_);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_publicKey,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_publicKey,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.publicKey();
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "publicKey", ApiRequestStatus.ERROR, duration_);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_publicKey, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_publicKey,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_publicKey, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "publicKey", ApiRequestStatus.OKAY, duration_);
		return res;
	}

	public void configurationChanged() {
		
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "configurationChanged", ApiRequestStatus.START, duration_);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_configurationChanged,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_configurationChanged,"self:" + ManagementServer.object2ref(this));
		try {
			 controller.configurationChanged();
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "configurationChanged", ApiRequestStatus.ERROR, duration_);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_configurationChanged, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_configurationChanged,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_configurationChanged, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "configurationChanged", ApiRequestStatus.OKAY, duration_);
		
	}

	public void updateStreams(EList<org.openecomp.dcae.controller.core.stream.DcaeStream> inputStreams, EList<org.openecomp.dcae.controller.core.stream.DcaeStream> outputStreams) {
		
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "updateStreams", ApiRequestStatus.START, duration_,inputStreams,outputStreams);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_updateStreams,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_updateStreams,"self:" + ManagementServer.object2ref(this));
		try {
			 controller.updateStreams(inputStreams,outputStreams);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "updateStreams", ApiRequestStatus.ERROR, duration_,inputStreams,outputStreams);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_updateStreams, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_updateStreams,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_updateStreams, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "updateStreams", ApiRequestStatus.OKAY, duration_,inputStreams,outputStreams);
		
	}

	public void logs(org.json.JSONObject cx, EList<org.openecomp.ncomp.core.logs.LogMessage> logs) {
		
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "logs", ApiRequestStatus.START, duration_,cx,logs);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_logs,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_logs,"self:" + ManagementServer.object2ref(this));
		try {
			 controller.logs(cx,logs);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "logs", ApiRequestStatus.ERROR, duration_,cx,logs);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_logs, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_logs,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_logs, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "logs", ApiRequestStatus.OKAY, duration_,cx,logs);
		
	}

	public void metrics(org.json.JSONObject cx, EList<org.openecomp.ncomp.core.metrics.Metric> metrics) {
		
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "metrics", ApiRequestStatus.START, duration_,cx,metrics);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_metrics,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_metrics,"self:" + ManagementServer.object2ref(this));
		try {
			 controller.metrics(cx,metrics);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "metrics", ApiRequestStatus.ERROR, duration_,cx,metrics);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_metrics, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_metrics,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_metrics, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "metrics", ApiRequestStatus.OKAY, duration_,cx,metrics);
		
	}

	public void properties(org.json.JSONObject cx, EList<org.openecomp.ncomp.sirius.manager.properties.AbstractProperty> l) {
		
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "properties", ApiRequestStatus.START, duration_,cx,l);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_properties,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_properties,"self:" + ManagementServer.object2ref(this));
		try {
			 controller.properties(cx,l);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "properties", ApiRequestStatus.ERROR, duration_,cx,l);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_properties, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_properties,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_properties, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "properties", ApiRequestStatus.OKAY, duration_,cx,l);
		
	}

	public void uploadInfo(org.json.JSONObject cx, EList<org.openecomp.ncomp.sirius.manager.server.ManagementInfo> info) {
		
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "uploadInfo", ApiRequestStatus.START, duration_,cx,info);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_uploadInfo,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_uploadInfo,"self:" + ManagementServer.object2ref(this));
		try {
			 controller.uploadInfo(cx,info);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "uploadInfo", ApiRequestStatus.ERROR, duration_,cx,info);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_uploadInfo, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_uploadInfo,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_uploadInfo, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "uploadInfo", ApiRequestStatus.OKAY, duration_,cx,info);
		
	}

	public EList<org.openecomp.ncomp.core.metrics.DoubleMetric> getValues(org.json.JSONObject cx, java.lang.String path, java.lang.Long start, java.lang.Long end, org.openecomp.ncomp.core.metrics.MetricValueOption option, boolean relativeInterval) {
		EList<org.openecomp.ncomp.core.metrics.DoubleMetric> res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "getValues", ApiRequestStatus.START, duration_,cx,path,start,end,option,relativeInterval);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_getValues,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_getValues,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.getValues(cx,path,start,end,option,relativeInterval);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "getValues", ApiRequestStatus.ERROR, duration_,cx,path,start,end,option,relativeInterval);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_getValues, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_getValues,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_getValues, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "getValues", ApiRequestStatus.OKAY, duration_,cx,path,start,end,option,relativeInterval);
		return res;
	}

	public EList<org.openecomp.ncomp.core.metrics.DoubleMetric> getValuesAll(org.json.JSONObject cx, java.lang.String path, EList<java.lang.String> metrics, java.lang.Long start, java.lang.Long end, org.openecomp.ncomp.core.metrics.MetricValueOption option, boolean relativeInterval) {
		EList<org.openecomp.ncomp.core.metrics.DoubleMetric> res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "getValuesAll", ApiRequestStatus.START, duration_,cx,path,metrics,start,end,option,relativeInterval);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_getValuesAll,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_getValuesAll,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.getValuesAll(cx,path,metrics,start,end,option,relativeInterval);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "getValuesAll", ApiRequestStatus.ERROR, duration_,cx,path,metrics,start,end,option,relativeInterval);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_getValuesAll, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_getValuesAll,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_getValuesAll, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "getValuesAll", ApiRequestStatus.OKAY, duration_,cx,path,metrics,start,end,option,relativeInterval);
		return res;
	}

	public EList<org.openecomp.ncomp.core.logs.LogMessage> getMessages(org.json.JSONObject cx, java.lang.String path, java.lang.Long start, java.lang.Long end) {
		EList<org.openecomp.ncomp.core.logs.LogMessage> res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "getMessages", ApiRequestStatus.START, duration_,cx,path,start,end);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_getMessages,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_getMessages,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.getMessages(cx,path,start,end);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "getMessages", ApiRequestStatus.ERROR, duration_,cx,path,start,end);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_getMessages, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_getMessages,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_getMessages, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "getMessages", ApiRequestStatus.OKAY, duration_,cx,path,start,end);
		return res;
	}

	public org.openecomp.ncomp.sirius.manager.server.LoggerInfo getRequestLogger(java.lang.String userName, java.lang.String action, java.lang.String resourcePath, org.json.JSONObject context) {
		org.openecomp.ncomp.sirius.manager.server.LoggerInfo res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "getRequestLogger", ApiRequestStatus.START, duration_,userName,action,resourcePath,context);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_getRequestLogger,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_getRequestLogger,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.getRequestLogger(userName,action,resourcePath,context);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "getRequestLogger", ApiRequestStatus.ERROR, duration_,userName,action,resourcePath,context);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_getRequestLogger, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_getRequestLogger,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_getRequestLogger, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "getRequestLogger", ApiRequestStatus.OKAY, duration_,userName,action,resourcePath,context);
		return res;
	}

	public EList<org.openecomp.ncomp.core.function.ValuePair> evaluate(java.lang.String path, org.openecomp.ncomp.core.function.Function function) {
		EList<org.openecomp.ncomp.core.function.ValuePair> res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "evaluate", ApiRequestStatus.START, duration_,path,function);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_evaluate,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_evaluate,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.evaluate(path,function);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "evaluate", ApiRequestStatus.ERROR, duration_,path,function);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_evaluate, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_evaluate,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_evaluate, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "evaluate", ApiRequestStatus.OKAY, duration_,path,function);
		return res;
	}

	public void update(java.lang.String path, org.openecomp.ncomp.core.function.Function function) {
		
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "update", ApiRequestStatus.START, duration_,path,function);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_update,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_update,"self:" + ManagementServer.object2ref(this));
		try {
			 controller.update(path,function);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "update", ApiRequestStatus.ERROR, duration_,path,function);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_update, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_update,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_update, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "update", ApiRequestStatus.OKAY, duration_,path,function);
		
	}

	public java.lang.String createNamespace(java.lang.String namespace) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "createNamespace", ApiRequestStatus.START, duration_,namespace);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_createNamespace,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_createNamespace,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.createNamespace(namespace);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "createNamespace", ApiRequestStatus.ERROR, duration_,namespace);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_createNamespace, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_createNamespace,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_createNamespace, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "createNamespace", ApiRequestStatus.OKAY, duration_,namespace);
		return res;
	}

	public java.lang.String deleteNamespace(java.lang.String namespace) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "deleteNamespace", ApiRequestStatus.START, duration_,namespace);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_deleteNamespace,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_deleteNamespace,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.deleteNamespace(namespace);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "deleteNamespace", ApiRequestStatus.ERROR, duration_,namespace);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_deleteNamespace, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_deleteNamespace,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_deleteNamespace, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "deleteNamespace", ApiRequestStatus.OKAY, duration_,namespace);
		return res;
	}

	public java.lang.String deployApp(java.lang.String namespace, java.lang.String jarfile) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "deployApp", ApiRequestStatus.START, duration_,namespace,jarfile);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_deployApp,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_deployApp,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.deployApp(namespace,jarfile);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "deployApp", ApiRequestStatus.ERROR, duration_,namespace,jarfile);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_deployApp, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_deployApp,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_deployApp, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "deployApp", ApiRequestStatus.OKAY, duration_,namespace,jarfile);
		return res;
	}

	public java.lang.String loadArtifact(java.lang.String namespace, java.lang.String artifactName, java.lang.String jarfile, java.lang.String version) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "loadArtifact", ApiRequestStatus.START, duration_,namespace,artifactName,jarfile,version);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_loadArtifact,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_loadArtifact,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.loadArtifact(namespace,artifactName,jarfile,version);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "loadArtifact", ApiRequestStatus.ERROR, duration_,namespace,artifactName,jarfile,version);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_loadArtifact, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_loadArtifact,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_loadArtifact, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "loadArtifact", ApiRequestStatus.OKAY, duration_,namespace,artifactName,jarfile,version);
		return res;
	}

	public java.lang.String loadArtifactWithConfig(java.lang.String namespace, java.lang.String artifactName, java.lang.String jarfile, java.lang.String version, java.lang.String config) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "loadArtifactWithConfig", ApiRequestStatus.START, duration_,namespace,artifactName,jarfile,version,config);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_loadArtifactWithConfig,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_loadArtifactWithConfig,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.loadArtifactWithConfig(namespace,artifactName,jarfile,version,config);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "loadArtifactWithConfig", ApiRequestStatus.ERROR, duration_,namespace,artifactName,jarfile,version,config);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_loadArtifactWithConfig, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_loadArtifactWithConfig,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_loadArtifactWithConfig, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "loadArtifactWithConfig", ApiRequestStatus.OKAY, duration_,namespace,artifactName,jarfile,version,config);
		return res;
	}

	public java.lang.String deleteArtifact(java.lang.String namespace, java.lang.String artifactName, java.lang.String artifactVersion) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "deleteArtifact", ApiRequestStatus.START, duration_,namespace,artifactName,artifactVersion);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_deleteArtifact,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_deleteArtifact,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.deleteArtifact(namespace,artifactName,artifactVersion);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "deleteArtifact", ApiRequestStatus.ERROR, duration_,namespace,artifactName,artifactVersion);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_deleteArtifact, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_deleteArtifact,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_deleteArtifact, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "deleteArtifact", ApiRequestStatus.OKAY, duration_,namespace,artifactName,artifactVersion);
		return res;
	}

	public java.lang.String startFlow(java.lang.String namespace, java.lang.String appName, java.lang.String flowId, java.lang.String extraArgs) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "startFlow", ApiRequestStatus.START, duration_,namespace,appName,flowId,extraArgs);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_startFlow,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_startFlow,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.startFlow(namespace,appName,flowId,extraArgs);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "startFlow", ApiRequestStatus.ERROR, duration_,namespace,appName,flowId,extraArgs);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_startFlow, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_startFlow,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_startFlow, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "startFlow", ApiRequestStatus.OKAY, duration_,namespace,appName,flowId,extraArgs);
		return res;
	}

	public java.lang.String startWorker(java.lang.String namespace, java.lang.String appName, java.lang.String workerId, java.lang.String extraArgs) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "startWorker", ApiRequestStatus.START, duration_,namespace,appName,workerId,extraArgs);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_startWorker,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_startWorker,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.startWorker(namespace,appName,workerId,extraArgs);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "startWorker", ApiRequestStatus.ERROR, duration_,namespace,appName,workerId,extraArgs);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_startWorker, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_startWorker,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_startWorker, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "startWorker", ApiRequestStatus.OKAY, duration_,namespace,appName,workerId,extraArgs);
		return res;
	}

	public java.lang.String startService(java.lang.String namespace, java.lang.String appName, java.lang.String serviceId, java.lang.String extraArgs) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "startService", ApiRequestStatus.START, duration_,namespace,appName,serviceId,extraArgs);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_startService,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_startService,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.startService(namespace,appName,serviceId,extraArgs);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "startService", ApiRequestStatus.ERROR, duration_,namespace,appName,serviceId,extraArgs);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_startService, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_startService,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_startService, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "startService", ApiRequestStatus.OKAY, duration_,namespace,appName,serviceId,extraArgs);
		return res;
	}

	public java.lang.String startApp(java.lang.String namespace, java.lang.String appName) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "startApp", ApiRequestStatus.START, duration_,namespace,appName);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_startApp,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_startApp,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.startApp(namespace,appName);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "startApp", ApiRequestStatus.ERROR, duration_,namespace,appName);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_startApp, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_startApp,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_startApp, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "startApp", ApiRequestStatus.OKAY, duration_,namespace,appName);
		return res;
	}

	public java.lang.String stopApp(java.lang.String namespace, java.lang.String appName) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "stopApp", ApiRequestStatus.START, duration_,namespace,appName);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_stopApp,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_stopApp,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.stopApp(namespace,appName);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "stopApp", ApiRequestStatus.ERROR, duration_,namespace,appName);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_stopApp, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_stopApp,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_stopApp, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "stopApp", ApiRequestStatus.OKAY, duration_,namespace,appName);
		return res;
	}

	public java.lang.String deleteApp(java.lang.String namespace, java.lang.String appName) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "deleteApp", ApiRequestStatus.START, duration_,namespace,appName);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_deleteApp,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_deleteApp,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.deleteApp(namespace,appName);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "deleteApp", ApiRequestStatus.ERROR, duration_,namespace,appName);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_deleteApp, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_deleteApp,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_deleteApp, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "deleteApp", ApiRequestStatus.OKAY, duration_,namespace,appName);
		return res;
	}

	public java.lang.String loadPreferencesApp(java.lang.String namespace, java.lang.String prefsFile, java.lang.String appId) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "loadPreferencesApp", ApiRequestStatus.START, duration_,namespace,prefsFile,appId);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_loadPreferencesApp,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_loadPreferencesApp,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.loadPreferencesApp(namespace,prefsFile,appId);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "loadPreferencesApp", ApiRequestStatus.ERROR, duration_,namespace,prefsFile,appId);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_loadPreferencesApp, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_loadPreferencesApp,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_loadPreferencesApp, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "loadPreferencesApp", ApiRequestStatus.OKAY, duration_,namespace,prefsFile,appId);
		return res;
	}

	public java.lang.String loadPreferencesFlow(java.lang.String namespace, java.lang.String prefsFile, java.lang.String appId, java.lang.String flowId) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "loadPreferencesFlow", ApiRequestStatus.START, duration_,namespace,prefsFile,appId,flowId);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_loadPreferencesFlow,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_loadPreferencesFlow,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.loadPreferencesFlow(namespace,prefsFile,appId,flowId);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "loadPreferencesFlow", ApiRequestStatus.ERROR, duration_,namespace,prefsFile,appId,flowId);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_loadPreferencesFlow, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_loadPreferencesFlow,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_loadPreferencesFlow, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "loadPreferencesFlow", ApiRequestStatus.OKAY, duration_,namespace,prefsFile,appId,flowId);
		return res;
	}

	public java.lang.String loadPreferencesNameSpace(java.lang.String namespace, java.lang.String prefsFile) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "loadPreferencesNameSpace", ApiRequestStatus.START, duration_,namespace,prefsFile);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_loadPreferencesNameSpace,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_loadPreferencesNameSpace,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.loadPreferencesNameSpace(namespace,prefsFile);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "loadPreferencesNameSpace", ApiRequestStatus.ERROR, duration_,namespace,prefsFile);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_loadPreferencesNameSpace, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_loadPreferencesNameSpace,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_loadPreferencesNameSpace, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "loadPreferencesNameSpace", ApiRequestStatus.OKAY, duration_,namespace,prefsFile);
		return res;
	}

	public java.lang.String setPreferencesApp(java.lang.String namespace, java.lang.String prefsString, java.lang.String appId) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "setPreferencesApp", ApiRequestStatus.START, duration_,namespace,prefsString,appId);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_setPreferencesApp,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_setPreferencesApp,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.setPreferencesApp(namespace,prefsString,appId);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "setPreferencesApp", ApiRequestStatus.ERROR, duration_,namespace,prefsString,appId);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_setPreferencesApp, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_setPreferencesApp,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_setPreferencesApp, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "setPreferencesApp", ApiRequestStatus.OKAY, duration_,namespace,prefsString,appId);
		return res;
	}

	public java.lang.String setPreferencesFlow(java.lang.String namespace, java.lang.String prefsString, java.lang.String appId, java.lang.String flowId) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "setPreferencesFlow", ApiRequestStatus.START, duration_,namespace,prefsString,appId,flowId);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_setPreferencesFlow,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_setPreferencesFlow,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.setPreferencesFlow(namespace,prefsString,appId,flowId);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "setPreferencesFlow", ApiRequestStatus.ERROR, duration_,namespace,prefsString,appId,flowId);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_setPreferencesFlow, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_setPreferencesFlow,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_setPreferencesFlow, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "setPreferencesFlow", ApiRequestStatus.OKAY, duration_,namespace,prefsString,appId,flowId);
		return res;
	}

	public java.lang.String setPreferencesWorker(java.lang.String namespace, java.lang.String prefsString, java.lang.String appId, java.lang.String workerId) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "setPreferencesWorker", ApiRequestStatus.START, duration_,namespace,prefsString,appId,workerId);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_setPreferencesWorker,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_setPreferencesWorker,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.setPreferencesWorker(namespace,prefsString,appId,workerId);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "setPreferencesWorker", ApiRequestStatus.ERROR, duration_,namespace,prefsString,appId,workerId);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_setPreferencesWorker, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_setPreferencesWorker,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_setPreferencesWorker, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "setPreferencesWorker", ApiRequestStatus.OKAY, duration_,namespace,prefsString,appId,workerId);
		return res;
	}

	public java.lang.String setPreferencesService(java.lang.String namespace, java.lang.String prefsString, java.lang.String appId, java.lang.String serviceId) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "setPreferencesService", ApiRequestStatus.START, duration_,namespace,prefsString,appId,serviceId);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_setPreferencesService,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_setPreferencesService,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.setPreferencesService(namespace,prefsString,appId,serviceId);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "setPreferencesService", ApiRequestStatus.ERROR, duration_,namespace,prefsString,appId,serviceId);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_setPreferencesService, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_setPreferencesService,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_setPreferencesService, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "setPreferencesService", ApiRequestStatus.OKAY, duration_,namespace,prefsString,appId,serviceId);
		return res;
	}

	public java.lang.String setPreferencesNameSpace(java.lang.String namespace, java.lang.String prefsString) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "setPreferencesNameSpace", ApiRequestStatus.START, duration_,namespace,prefsString);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_setPreferencesNameSpace,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_setPreferencesNameSpace,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.setPreferencesNameSpace(namespace,prefsString);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "setPreferencesNameSpace", ApiRequestStatus.ERROR, duration_,namespace,prefsString);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_setPreferencesNameSpace, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_setPreferencesNameSpace,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_setPreferencesNameSpace, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "setPreferencesNameSpace", ApiRequestStatus.OKAY, duration_,namespace,prefsString);
		return res;
	}

	public java.lang.String setFlowRunTimeArgs(java.lang.String namespace, java.lang.String appId, java.lang.String flowId, java.lang.String args) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "setFlowRunTimeArgs", ApiRequestStatus.START, duration_,namespace,appId,flowId,args);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_setFlowRunTimeArgs,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_setFlowRunTimeArgs,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.setFlowRunTimeArgs(namespace,appId,flowId,args);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "setFlowRunTimeArgs", ApiRequestStatus.ERROR, duration_,namespace,appId,flowId,args);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_setFlowRunTimeArgs, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_setFlowRunTimeArgs,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_setFlowRunTimeArgs, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "setFlowRunTimeArgs", ApiRequestStatus.OKAY, duration_,namespace,appId,flowId,args);
		return res;
	}

	public java.lang.String setFlowletInstances(java.lang.String namespace, java.lang.String appId, java.lang.String flowId, java.lang.String flowletId, int nInstances) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "setFlowletInstances", ApiRequestStatus.START, duration_,namespace,appId,flowId,flowletId,nInstances);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_setFlowletInstances,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_setFlowletInstances,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.setFlowletInstances(namespace,appId,flowId,flowletId,nInstances);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "setFlowletInstances", ApiRequestStatus.ERROR, duration_,namespace,appId,flowId,flowletId,nInstances);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_setFlowletInstances, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_setFlowletInstances,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_setFlowletInstances, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "setFlowletInstances", ApiRequestStatus.OKAY, duration_,namespace,appId,flowId,flowletId,nInstances);
		return res;
	}

	public java.lang.String stopFlow(java.lang.String namespace, java.lang.String appId, java.lang.String flowId) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "stopFlow", ApiRequestStatus.START, duration_,namespace,appId,flowId);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_stopFlow,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_stopFlow,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.stopFlow(namespace,appId,flowId);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "stopFlow", ApiRequestStatus.ERROR, duration_,namespace,appId,flowId);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_stopFlow, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_stopFlow,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_stopFlow, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "stopFlow", ApiRequestStatus.OKAY, duration_,namespace,appId,flowId);
		return res;
	}

	public java.lang.String stopWorker(java.lang.String namespace, java.lang.String appId, java.lang.String workerId) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "stopWorker", ApiRequestStatus.START, duration_,namespace,appId,workerId);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_stopWorker,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_stopWorker,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.stopWorker(namespace,appId,workerId);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "stopWorker", ApiRequestStatus.ERROR, duration_,namespace,appId,workerId);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_stopWorker, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_stopWorker,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_stopWorker, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "stopWorker", ApiRequestStatus.OKAY, duration_,namespace,appId,workerId);
		return res;
	}

	public java.lang.String stopService(java.lang.String namespace, java.lang.String appId, java.lang.String serviceId) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "stopService", ApiRequestStatus.START, duration_,namespace,appId,serviceId);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_stopService,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_stopService,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.stopService(namespace,appId,serviceId);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "stopService", ApiRequestStatus.ERROR, duration_,namespace,appId,serviceId);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_stopService, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_stopService,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_stopService, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "stopService", ApiRequestStatus.OKAY, duration_,namespace,appId,serviceId);
		return res;
	}

	public java.lang.String truncateDataSet(java.lang.String namespace, java.lang.String datasetName) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "truncateDataSet", ApiRequestStatus.START, duration_,namespace,datasetName);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_truncateDataSet,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_truncateDataSet,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.truncateDataSet(namespace,datasetName);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "truncateDataSet", ApiRequestStatus.ERROR, duration_,namespace,datasetName);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_truncateDataSet, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_truncateDataSet,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_truncateDataSet, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "truncateDataSet", ApiRequestStatus.OKAY, duration_,namespace,datasetName);
		return res;
	}

	public java.lang.String deleteDataset(java.lang.String namespace, java.lang.String datasetName) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "deleteDataset", ApiRequestStatus.START, duration_,namespace,datasetName);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_deleteDataset,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_deleteDataset,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.deleteDataset(namespace,datasetName);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "deleteDataset", ApiRequestStatus.ERROR, duration_,namespace,datasetName);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_deleteDataset, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_deleteDataset,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_deleteDataset, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "deleteDataset", ApiRequestStatus.OKAY, duration_,namespace,datasetName);
		return res;
	}

	public java.lang.String createStream(java.lang.String namespace, java.lang.String newStreamId) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "createStream", ApiRequestStatus.START, duration_,namespace,newStreamId);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_createStream,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_createStream,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.createStream(namespace,newStreamId);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "createStream", ApiRequestStatus.ERROR, duration_,namespace,newStreamId);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_createStream, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_createStream,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_createStream, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "createStream", ApiRequestStatus.OKAY, duration_,namespace,newStreamId);
		return res;
	}

	public java.lang.String deleteStream(java.lang.String namespace, java.lang.String streamId) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "deleteStream", ApiRequestStatus.START, duration_,namespace,streamId);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_deleteStream,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_deleteStream,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.deleteStream(namespace,streamId);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "deleteStream", ApiRequestStatus.ERROR, duration_,namespace,streamId);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_deleteStream, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_deleteStream,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_deleteStream, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "deleteStream", ApiRequestStatus.OKAY, duration_,namespace,streamId);
		return res;
	}

	public EList<java.lang.String> getStreamEvents(java.lang.String namespace, java.lang.String streamId, java.lang.String startTime, java.lang.String endTime, int limit) {
		EList<java.lang.String> res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "getStreamEvents", ApiRequestStatus.START, duration_,namespace,streamId,startTime,endTime,limit);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_getStreamEvents,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_getStreamEvents,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.getStreamEvents(namespace,streamId,startTime,endTime,limit);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "getStreamEvents", ApiRequestStatus.ERROR, duration_,namespace,streamId,startTime,endTime,limit);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_getStreamEvents, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_getStreamEvents,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_getStreamEvents, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "getStreamEvents", ApiRequestStatus.OKAY, duration_,namespace,streamId,startTime,endTime,limit);
		return res;
	}

	public EList<java.lang.String> getStreamStats(java.lang.String namespace, java.lang.String streamId, java.lang.String startTime, java.lang.String endTime, int limit) {
		EList<java.lang.String> res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "getStreamStats", ApiRequestStatus.START, duration_,namespace,streamId,startTime,endTime,limit);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_getStreamStats,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_getStreamStats,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.getStreamStats(namespace,streamId,startTime,endTime,limit);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "getStreamStats", ApiRequestStatus.ERROR, duration_,namespace,streamId,startTime,endTime,limit);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_getStreamStats, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_getStreamStats,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_getStreamStats, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "getStreamStats", ApiRequestStatus.OKAY, duration_,namespace,streamId,startTime,endTime,limit);
		return res;
	}

	public java.lang.String sendEventToStream(java.lang.String namespace, java.lang.String streamId, java.lang.String event) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "sendEventToStream", ApiRequestStatus.START, duration_,namespace,streamId,event);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_sendEventToStream,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_sendEventToStream,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.sendEventToStream(namespace,streamId,event);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "sendEventToStream", ApiRequestStatus.ERROR, duration_,namespace,streamId,event);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_sendEventToStream, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_sendEventToStream,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_sendEventToStream, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "sendEventToStream", ApiRequestStatus.OKAY, duration_,namespace,streamId,event);
		return res;
	}

	public java.lang.String trucateStream(java.lang.String namespace, java.lang.String streamId) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "trucateStream", ApiRequestStatus.START, duration_,namespace,streamId);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_trucateStream,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_trucateStream,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.trucateStream(namespace,streamId);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "trucateStream", ApiRequestStatus.ERROR, duration_,namespace,streamId);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_trucateStream, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_trucateStream,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_trucateStream, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "trucateStream", ApiRequestStatus.OKAY, duration_,namespace,streamId);
		return res;
	}

	public java.lang.String setStreamProperties(java.lang.String namespace, java.lang.String streamId, java.lang.String propsFile) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "setStreamProperties", ApiRequestStatus.START, duration_,namespace,streamId,propsFile);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_setStreamProperties,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_setStreamProperties,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.setStreamProperties(namespace,streamId,propsFile);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "setStreamProperties", ApiRequestStatus.ERROR, duration_,namespace,streamId,propsFile);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_setStreamProperties, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_setStreamProperties,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_setStreamProperties, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "setStreamProperties", ApiRequestStatus.OKAY, duration_,namespace,streamId,propsFile);
		return res;
	}

	public java.lang.String restartApp(java.lang.String namespace, java.lang.String appId, java.lang.String progTypes) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "restartApp", ApiRequestStatus.START, duration_,namespace,appId,progTypes);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_restartApp,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_restartApp,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.restartApp(namespace,appId,progTypes);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "restartApp", ApiRequestStatus.ERROR, duration_,namespace,appId,progTypes);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_restartApp, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_restartApp,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_restartApp, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "restartApp", ApiRequestStatus.OKAY, duration_,namespace,appId,progTypes);
		return res;
	}

	public java.lang.String createApp(java.lang.String namespace, java.lang.String appId, java.lang.String artifactName, java.lang.String artifactVersion, java.lang.String scope) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "createApp", ApiRequestStatus.START, duration_,namespace,appId,artifactName,artifactVersion,scope);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_createApp,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_createApp,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.createApp(namespace,appId,artifactName,artifactVersion,scope);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "createApp", ApiRequestStatus.ERROR, duration_,namespace,appId,artifactName,artifactVersion,scope);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_createApp, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_createApp,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_createApp, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "createApp", ApiRequestStatus.OKAY, duration_,namespace,appId,artifactName,artifactVersion,scope);
		return res;
	}

	public java.lang.String createAppWithConfig(java.lang.String namespace, java.lang.String appId, java.lang.String artifactName, java.lang.String artifactVersion, java.lang.String scope, java.lang.String appConfig) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "createAppWithConfig", ApiRequestStatus.START, duration_,namespace,appId,artifactName,artifactVersion,scope,appConfig);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_createAppWithConfig,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_createAppWithConfig,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.createAppWithConfig(namespace,appId,artifactName,artifactVersion,scope,appConfig);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "createAppWithConfig", ApiRequestStatus.ERROR, duration_,namespace,appId,artifactName,artifactVersion,scope,appConfig);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_createAppWithConfig, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_createAppWithConfig,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_createAppWithConfig, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "createAppWithConfig", ApiRequestStatus.OKAY, duration_,namespace,appId,artifactName,artifactVersion,scope,appConfig);
		return res;
	}

	public java.lang.String setDatasetProperties(java.lang.String namespace, java.lang.String datasetName, java.lang.String datasetProperties) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "setDatasetProperties", ApiRequestStatus.START, duration_,namespace,datasetName,datasetProperties);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_setDatasetProperties,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_setDatasetProperties,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.setDatasetProperties(namespace,datasetName,datasetProperties);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "setDatasetProperties", ApiRequestStatus.ERROR, duration_,namespace,datasetName,datasetProperties);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_setDatasetProperties, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_setDatasetProperties,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_setDatasetProperties, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "setDatasetProperties", ApiRequestStatus.OKAY, duration_,namespace,datasetName,datasetProperties);
		return res;
	}

	public java.lang.String setStreamTTL(java.lang.String namespace, java.lang.String streamName, int ttlSeconds) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "setStreamTTL", ApiRequestStatus.START, duration_,namespace,streamName,ttlSeconds);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_setStreamTTL,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_setStreamTTL,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.setStreamTTL(namespace,streamName,ttlSeconds);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "setStreamTTL", ApiRequestStatus.ERROR, duration_,namespace,streamName,ttlSeconds);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_setStreamTTL, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_setStreamTTL,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_setStreamTTL, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "setStreamTTL", ApiRequestStatus.OKAY, duration_,namespace,streamName,ttlSeconds);
		return res;
	}

	public java.lang.String suspendSchedule(java.lang.String namespace, java.lang.String appId, java.lang.String scheduleId) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "suspendSchedule", ApiRequestStatus.START, duration_,namespace,appId,scheduleId);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_suspendSchedule,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_suspendSchedule,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.suspendSchedule(namespace,appId,scheduleId);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "suspendSchedule", ApiRequestStatus.ERROR, duration_,namespace,appId,scheduleId);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_suspendSchedule, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_suspendSchedule,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_suspendSchedule, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "suspendSchedule", ApiRequestStatus.OKAY, duration_,namespace,appId,scheduleId);
		return res;
	}

	public java.lang.String resumeSchedule(java.lang.String namespace, java.lang.String appId, java.lang.String scheduleId) {
		java.lang.String res = null;
		long duration_ = 0;
		if (server != null)
			server.getServer().recordApi(null, this, "resumeSchedule", ApiRequestStatus.START, duration_,namespace,appId,scheduleId);
		Date now_ = new Date();
		ecomplogger.recordAuditEventStartIfNeeded(CdapClusterManagerOperationEnum.CdapClusterManager_resumeSchedule,server,this);
		ecomplogger.recordMetricEventStart(CdapClusterManagerOperationEnum.CdapClusterManager_resumeSchedule,"self:" + ManagementServer.object2ref(this));
		try {
			res =  controller.resumeSchedule(namespace,appId,scheduleId);
		}
		catch (Exception e) {
			duration_ = new Date().getTime()-now_.getTime();
			if (server != null)
				server.getServer().recordApi(null, this, "resumeSchedule", ApiRequestStatus.ERROR, duration_,namespace,appId,scheduleId);
			System.err.println("ERROR: " + e);
			ecomplogger.warn(CdapClusterManagerMessageEnum.REQUEST_FAILED_resumeSchedule, e.toString());
			EcompException e1 =  EcompException.create(CdapClusterManagerMessageEnum.REQUEST_FAILED_resumeSchedule,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR, CdapClusterManagerMessageEnum.REQUEST_FAILED_resumeSchedule, e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		duration_ = new Date().getTime()-now_.getTime();
		if (server != null)
			server.getServer().recordApi(null, this, "resumeSchedule", ApiRequestStatus.OKAY, duration_,namespace,appId,scheduleId);
		return res;
	}








	public static void ecoreSetup() {
		DcaeCdapClusterManagerProvider.ecoreSetup();
	}
	public DcaeCdapClusterManagerProvider getSiriusProvider() {
		return controller;
	}
}
