
/*-
 * ============LICENSE_START==========================================
 * OPENECOMP - DCAE
 * ===================================================================
 * Copyright (c) 2017 AT&T Intellectual Property. All rights reserved.
 * ===================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0 
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END============================================
 */
	
// Autogenerated
// Do not edit. No need to extend this class.
package org.openecomp.dcae.controller.service.cdap.cluster.servers.manager;

import org.openecomp.ncomp.sirius.manager.AbstractClient;
import org.openecomp.ncomp.sirius.manager.HighAvailabilityClient;
import org.openecomp.ncomp.sirius.manager.GenericHttpClient;

import org.apache.log4j.Logger;

import org.openecomp.logger.EcompLogger;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EClass;

import org.openecomp.dcae.controller.service.cdap.cluster.manager.impl.CdapClusterManagerImpl;
import org.openecomp.dcae.controller.service.cdap.cluster.manager.ManagerPackage;
import org.openecomp.dcae.controller.service.cdap.cluster.servers.manager.logging.CdapClusterManagerOperationEnum;
import org.openecomp.dcae.controller.service.cdap.cluster.servers.manager.logging.CdapClusterManagerMessageEnum;





 
@SuppressWarnings("unchecked")
public class DcaeCdapClusterManagerClient extends CdapClusterManagerImpl {
	public static final Logger logger = Logger.getLogger(DcaeCdapClusterManagerClient.class);
	static final EcompLogger ecomplogger = EcompLogger.getEcompLogger();
	public AbstractClient client;

	public DcaeCdapClusterManagerClient(String file, String name) {
		DcaeCdapClusterManager.ecoreSetup(); 
		client = new GenericHttpClient(file,name);
		client.add("/resources", this);
	}

	public DcaeCdapClusterManagerClient(String file, String name1, String name2) {
		HighAvailabilityClient client1 = new HighAvailabilityClient(file,name1,name2);
		client = client1.all; // requests should be forwarded to all.
		client.add("/resources", this);
	}
	
	public DcaeCdapClusterManagerClient(AbstractClient c) {
		client = c;
		client.add("/resources", this);
	}



	@Override
	public org.openecomp.dcae.controller.core.service.HealthTestResponse test() {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_test);
		org.openecomp.dcae.controller.core.service.HealthTestResponse res;
		try {
		  res = (org.openecomp.dcae.controller.core.service.HealthTestResponse) client.operationPath("/resources", c, "test", null);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_test, e.toString());
			throw new RuntimeException("remote call failed:  test", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public void suspend() {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_suspend);
		
		try {
		  client.operationPath("/resources", c, "suspend", null);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_suspend, e.toString());
			throw new RuntimeException("remote call failed:  suspend", e);
		}
		ecomplogger.recordMetricEventEnd();
		
	}

	@Override
	public void resume() {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_resume);
		
		try {
		  client.operationPath("/resources", c, "resume", null);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_resume, e.toString());
			throw new RuntimeException("remote call failed:  resume", e);
		}
		ecomplogger.recordMetricEventEnd();
		
	}

	@Override
	public java.lang.String publicKey() {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_publicKey);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "publicKey", null);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_publicKey, e.toString());
			throw new RuntimeException("remote call failed:  publicKey", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public void configurationChanged() {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_configurationChanged);
		
		try {
		  client.operationPath("/resources", c, "configurationChanged", null);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_configurationChanged, e.toString());
			throw new RuntimeException("remote call failed:  configurationChanged", e);
		}
		ecomplogger.recordMetricEventEnd();
		
	}

	@Override
	public void updateStreams(EList<org.openecomp.dcae.controller.core.stream.DcaeStream> inputStreams, EList<org.openecomp.dcae.controller.core.stream.DcaeStream> outputStreams) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_updateStreams);
		
		try {
		  client.operationPath("/resources", c, "updateStreams", null, inputStreams,outputStreams);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_updateStreams, e.toString());
			throw new RuntimeException("remote call failed:  updateStreams", e);
		}
		ecomplogger.recordMetricEventEnd();
		
	}

	@Override
	public void logs(org.json.JSONObject cx, EList<org.openecomp.ncomp.core.logs.LogMessage> logs) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_logs);
		
		try {
		  client.operationPath("/resources", c, "logs", cx != null && cx.has("timeout") ? cx.getLong("timeout") : null, cx,logs);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_logs, e.toString());
			throw new RuntimeException("remote call failed:  logs", e);
		}
		ecomplogger.recordMetricEventEnd();
		
	}

	@Override
	public void metrics(org.json.JSONObject cx, EList<org.openecomp.ncomp.core.metrics.Metric> metrics) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_metrics);
		
		try {
		  client.operationPath("/resources", c, "metrics", cx != null && cx.has("timeout") ? cx.getLong("timeout") : null, cx,metrics);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_metrics, e.toString());
			throw new RuntimeException("remote call failed:  metrics", e);
		}
		ecomplogger.recordMetricEventEnd();
		
	}

	@Override
	public void properties(org.json.JSONObject cx, EList<org.openecomp.ncomp.sirius.manager.properties.AbstractProperty> l) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_properties);
		
		try {
		  client.operationPath("/resources", c, "properties", cx != null && cx.has("timeout") ? cx.getLong("timeout") : null, cx,l);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_properties, e.toString());
			throw new RuntimeException("remote call failed:  properties", e);
		}
		ecomplogger.recordMetricEventEnd();
		
	}

	@Override
	public void uploadInfo(org.json.JSONObject cx, EList<org.openecomp.ncomp.sirius.manager.server.ManagementInfo> info) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_uploadInfo);
		
		try {
		  client.operationPath("/resources", c, "uploadInfo", cx != null && cx.has("timeout") ? cx.getLong("timeout") : null, cx,info);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_uploadInfo, e.toString());
			throw new RuntimeException("remote call failed:  uploadInfo", e);
		}
		ecomplogger.recordMetricEventEnd();
		
	}

	@Override
	public EList<org.openecomp.ncomp.core.metrics.DoubleMetric> getValues(org.json.JSONObject cx, java.lang.String path, java.lang.Long start, java.lang.Long end, org.openecomp.ncomp.core.metrics.MetricValueOption option, boolean relativeInterval) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_getValues);
		EList<org.openecomp.ncomp.core.metrics.DoubleMetric> res;
		try {
		  res = (EList<org.openecomp.ncomp.core.metrics.DoubleMetric>) client.operationPath("/resources", c, "getValues", cx != null && cx.has("timeout") ? cx.getLong("timeout") : null, cx,path,start,end,option,relativeInterval);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_getValues, e.toString());
			throw new RuntimeException("remote call failed:  getValues", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public EList<org.openecomp.ncomp.core.metrics.DoubleMetric> getValuesAll(org.json.JSONObject cx, java.lang.String path, EList<java.lang.String> metrics, java.lang.Long start, java.lang.Long end, org.openecomp.ncomp.core.metrics.MetricValueOption option, boolean relativeInterval) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_getValuesAll);
		EList<org.openecomp.ncomp.core.metrics.DoubleMetric> res;
		try {
		  res = (EList<org.openecomp.ncomp.core.metrics.DoubleMetric>) client.operationPath("/resources", c, "getValuesAll", cx != null && cx.has("timeout") ? cx.getLong("timeout") : null, cx,path,metrics,start,end,option,relativeInterval);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_getValuesAll, e.toString());
			throw new RuntimeException("remote call failed:  getValuesAll", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public EList<org.openecomp.ncomp.core.logs.LogMessage> getMessages(org.json.JSONObject cx, java.lang.String path, java.lang.Long start, java.lang.Long end) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_getMessages);
		EList<org.openecomp.ncomp.core.logs.LogMessage> res;
		try {
		  res = (EList<org.openecomp.ncomp.core.logs.LogMessage>) client.operationPath("/resources", c, "getMessages", cx != null && cx.has("timeout") ? cx.getLong("timeout") : null, cx,path,start,end);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_getMessages, e.toString());
			throw new RuntimeException("remote call failed:  getMessages", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public org.openecomp.ncomp.sirius.manager.server.LoggerInfo getRequestLogger(java.lang.String userName, java.lang.String action, java.lang.String resourcePath, org.json.JSONObject context) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_getRequestLogger);
		org.openecomp.ncomp.sirius.manager.server.LoggerInfo res;
		try {
		  res = (org.openecomp.ncomp.sirius.manager.server.LoggerInfo) client.operationPath("/resources", c, "getRequestLogger", null, userName,action,resourcePath,context);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_getRequestLogger, e.toString());
			throw new RuntimeException("remote call failed:  getRequestLogger", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public EList<org.openecomp.ncomp.core.function.ValuePair> evaluate(java.lang.String path, org.openecomp.ncomp.core.function.Function function) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_evaluate);
		EList<org.openecomp.ncomp.core.function.ValuePair> res;
		try {
		  res = (EList<org.openecomp.ncomp.core.function.ValuePair>) client.operationPath("/resources", c, "evaluate", null, path,function);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_evaluate, e.toString());
			throw new RuntimeException("remote call failed:  evaluate", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public void update(java.lang.String path, org.openecomp.ncomp.core.function.Function function) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_update);
		
		try {
		  client.operationPath("/resources", c, "update", null, path,function);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_update, e.toString());
			throw new RuntimeException("remote call failed:  update", e);
		}
		ecomplogger.recordMetricEventEnd();
		
	}

	@Override
	public java.lang.String createNamespace(java.lang.String namespace) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_createNamespace);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "createNamespace", null, namespace);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_createNamespace, e.toString());
			throw new RuntimeException("remote call failed:  createNamespace", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String deleteNamespace(java.lang.String namespace) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_deleteNamespace);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "deleteNamespace", null, namespace);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_deleteNamespace, e.toString());
			throw new RuntimeException("remote call failed:  deleteNamespace", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String deployApp(java.lang.String namespace, java.lang.String jarfile) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_deployApp);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "deployApp", null, namespace,jarfile);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_deployApp, e.toString());
			throw new RuntimeException("remote call failed:  deployApp", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String loadArtifact(java.lang.String namespace, java.lang.String artifactName, java.lang.String jarfile, java.lang.String version) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_loadArtifact);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "loadArtifact", null, namespace,artifactName,jarfile,version);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_loadArtifact, e.toString());
			throw new RuntimeException("remote call failed:  loadArtifact", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String deleteArtifact(java.lang.String namespace, java.lang.String artifactName, java.lang.String artifactVersion) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_deleteArtifact);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "deleteArtifact", null, namespace,artifactName,artifactVersion);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_deleteArtifact, e.toString());
			throw new RuntimeException("remote call failed:  deleteArtifact", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String startFlow(java.lang.String namespace, java.lang.String appName, java.lang.String flowId, java.lang.String extraArgs) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_startFlow);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "startFlow", null, namespace,appName,flowId,extraArgs);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_startFlow, e.toString());
			throw new RuntimeException("remote call failed:  startFlow", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String startWorker(java.lang.String namespace, java.lang.String appName, java.lang.String workerId, java.lang.String extraArgs) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_startWorker);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "startWorker", null, namespace,appName,workerId,extraArgs);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_startWorker, e.toString());
			throw new RuntimeException("remote call failed:  startWorker", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String startService(java.lang.String namespace, java.lang.String appName, java.lang.String serviceId, java.lang.String extraArgs) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_startService);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "startService", null, namespace,appName,serviceId,extraArgs);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_startService, e.toString());
			throw new RuntimeException("remote call failed:  startService", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String startApp(java.lang.String namespace, java.lang.String appName) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_startApp);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "startApp", null, namespace,appName);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_startApp, e.toString());
			throw new RuntimeException("remote call failed:  startApp", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String stopApp(java.lang.String namespace, java.lang.String appName) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_stopApp);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "stopApp", null, namespace,appName);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_stopApp, e.toString());
			throw new RuntimeException("remote call failed:  stopApp", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String deleteApp(java.lang.String namespace, java.lang.String appName) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_deleteApp);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "deleteApp", null, namespace,appName);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_deleteApp, e.toString());
			throw new RuntimeException("remote call failed:  deleteApp", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String loadPreferencesApp(java.lang.String namespace, java.lang.String prefsFile, java.lang.String appId) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_loadPreferencesApp);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "loadPreferencesApp", null, namespace,prefsFile,appId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_loadPreferencesApp, e.toString());
			throw new RuntimeException("remote call failed:  loadPreferencesApp", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String loadPreferencesFlow(java.lang.String namespace, java.lang.String prefsFile, java.lang.String appId, java.lang.String flowId) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_loadPreferencesFlow);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "loadPreferencesFlow", null, namespace,prefsFile,appId,flowId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_loadPreferencesFlow, e.toString());
			throw new RuntimeException("remote call failed:  loadPreferencesFlow", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String loadPreferencesNameSpace(java.lang.String namespace, java.lang.String prefsFile) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_loadPreferencesNameSpace);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "loadPreferencesNameSpace", null, namespace,prefsFile);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_loadPreferencesNameSpace, e.toString());
			throw new RuntimeException("remote call failed:  loadPreferencesNameSpace", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String setPreferencesApp(java.lang.String namespace, java.lang.String prefsString, java.lang.String appId) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_setPreferencesApp);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "setPreferencesApp", null, namespace,prefsString,appId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_setPreferencesApp, e.toString());
			throw new RuntimeException("remote call failed:  setPreferencesApp", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String setPreferencesFlow(java.lang.String namespace, java.lang.String prefsString, java.lang.String appId, java.lang.String flowId) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_setPreferencesFlow);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "setPreferencesFlow", null, namespace,prefsString,appId,flowId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_setPreferencesFlow, e.toString());
			throw new RuntimeException("remote call failed:  setPreferencesFlow", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String setPreferencesWorker(java.lang.String namespace, java.lang.String prefsString, java.lang.String appId, java.lang.String workerId) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_setPreferencesWorker);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "setPreferencesWorker", null, namespace,prefsString,appId,workerId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_setPreferencesWorker, e.toString());
			throw new RuntimeException("remote call failed:  setPreferencesWorker", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String setPreferencesService(java.lang.String namespace, java.lang.String prefsString, java.lang.String appId, java.lang.String serviceId) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_setPreferencesService);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "setPreferencesService", null, namespace,prefsString,appId,serviceId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_setPreferencesService, e.toString());
			throw new RuntimeException("remote call failed:  setPreferencesService", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String setPreferencesNameSpace(java.lang.String namespace, java.lang.String prefsString) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_setPreferencesNameSpace);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "setPreferencesNameSpace", null, namespace,prefsString);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_setPreferencesNameSpace, e.toString());
			throw new RuntimeException("remote call failed:  setPreferencesNameSpace", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String setFlowRunTimeArgs(java.lang.String namespace, java.lang.String appId, java.lang.String flowId, java.lang.String args) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_setFlowRunTimeArgs);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "setFlowRunTimeArgs", null, namespace,appId,flowId,args);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_setFlowRunTimeArgs, e.toString());
			throw new RuntimeException("remote call failed:  setFlowRunTimeArgs", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String setFlowletInstances(java.lang.String namespace, java.lang.String appId, java.lang.String flowId, java.lang.String flowletId, int nInstances) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_setFlowletInstances);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "setFlowletInstances", null, namespace,appId,flowId,flowletId,nInstances);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_setFlowletInstances, e.toString());
			throw new RuntimeException("remote call failed:  setFlowletInstances", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String stopFlow(java.lang.String namespace, java.lang.String appId, java.lang.String flowId) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_stopFlow);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "stopFlow", null, namespace,appId,flowId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_stopFlow, e.toString());
			throw new RuntimeException("remote call failed:  stopFlow", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String stopWorker(java.lang.String namespace, java.lang.String appId, java.lang.String workerId) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_stopWorker);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "stopWorker", null, namespace,appId,workerId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_stopWorker, e.toString());
			throw new RuntimeException("remote call failed:  stopWorker", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String stopService(java.lang.String namespace, java.lang.String appId, java.lang.String serviceId) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_stopService);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "stopService", null, namespace,appId,serviceId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_stopService, e.toString());
			throw new RuntimeException("remote call failed:  stopService", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String truncateDataSet(java.lang.String namespace, java.lang.String datasetName) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_truncateDataSet);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "truncateDataSet", null, namespace,datasetName);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_truncateDataSet, e.toString());
			throw new RuntimeException("remote call failed:  truncateDataSet", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String deleteDataset(java.lang.String namespace, java.lang.String datasetName) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_deleteDataset);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "deleteDataset", null, namespace,datasetName);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_deleteDataset, e.toString());
			throw new RuntimeException("remote call failed:  deleteDataset", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String createStream(java.lang.String namespace, java.lang.String newStreamId) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_createStream);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "createStream", null, namespace,newStreamId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_createStream, e.toString());
			throw new RuntimeException("remote call failed:  createStream", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String deleteStream(java.lang.String namespace, java.lang.String streamId) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_deleteStream);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "deleteStream", null, namespace,streamId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_deleteStream, e.toString());
			throw new RuntimeException("remote call failed:  deleteStream", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public EList<java.lang.String> getStreamEvents(java.lang.String namespace, java.lang.String streamId, java.lang.String startTime, java.lang.String endTime, int limit) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_getStreamEvents);
		EList<java.lang.String> res;
		try {
		  res = (EList<java.lang.String>) client.operationPath("/resources", c, "getStreamEvents", null, namespace,streamId,startTime,endTime,limit);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_getStreamEvents, e.toString());
			throw new RuntimeException("remote call failed:  getStreamEvents", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public EList<java.lang.String> getStreamStats(java.lang.String namespace, java.lang.String streamId, java.lang.String startTime, java.lang.String endTime, int limit) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_getStreamStats);
		EList<java.lang.String> res;
		try {
		  res = (EList<java.lang.String>) client.operationPath("/resources", c, "getStreamStats", null, namespace,streamId,startTime,endTime,limit);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_getStreamStats, e.toString());
			throw new RuntimeException("remote call failed:  getStreamStats", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String sendEventToStream(java.lang.String namespace, java.lang.String streamId, java.lang.String event) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_sendEventToStream);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "sendEventToStream", null, namespace,streamId,event);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_sendEventToStream, e.toString());
			throw new RuntimeException("remote call failed:  sendEventToStream", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String trucateStream(java.lang.String namespace, java.lang.String streamId) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_trucateStream);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "trucateStream", null, namespace,streamId);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_trucateStream, e.toString());
			throw new RuntimeException("remote call failed:  trucateStream", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String setStreamProperties(java.lang.String namespace, java.lang.String streamId, java.lang.String propsFile) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_setStreamProperties);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "setStreamProperties", null, namespace,streamId,propsFile);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_setStreamProperties, e.toString());
			throw new RuntimeException("remote call failed:  setStreamProperties", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String restartApp(java.lang.String namespace, java.lang.String appId, java.lang.String progTypes) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_restartApp);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "restartApp", null, namespace,appId,progTypes);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_restartApp, e.toString());
			throw new RuntimeException("remote call failed:  restartApp", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String createApp(java.lang.String namespace, java.lang.String appId, java.lang.String artifactName, java.lang.String artifactVersion, java.lang.String scope) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_createApp);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "createApp", null, namespace,appId,artifactName,artifactVersion,scope);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_createApp, e.toString());
			throw new RuntimeException("remote call failed:  createApp", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String createAppWithConfig(java.lang.String namespace, java.lang.String appId, java.lang.String artifactName, java.lang.String artifactVersion, java.lang.String scope, java.lang.String appConfig) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_createAppWithConfig);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "createAppWithConfig", null, namespace,appId,artifactName,artifactVersion,scope,appConfig);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_createAppWithConfig, e.toString());
			throw new RuntimeException("remote call failed:  createAppWithConfig", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String setDatasetProperties(java.lang.String namespace, java.lang.String datasetName, java.lang.String datasetProperties) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_setDatasetProperties);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "setDatasetProperties", null, namespace,datasetName,datasetProperties);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_setDatasetProperties, e.toString());
			throw new RuntimeException("remote call failed:  setDatasetProperties", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public java.lang.String setStreamTTL(java.lang.String namespace, java.lang.String streamName, int ttlSeconds) {
		EClass c = ManagerPackage.eINSTANCE.getCdapClusterManager(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(CdapClusterManagerOperationEnum.REMOTE_setStreamTTL);
		java.lang.String res;
		try {
		  res = (java.lang.String) client.operationPath("/resources", c, "setStreamTTL", null, namespace,streamName,ttlSeconds);
		}
		catch (Exception e) {
			ecomplogger.warn(CdapClusterManagerMessageEnum.REMOTE_setStreamTTL, e.toString());
			throw new RuntimeException("remote call failed:  setStreamTTL", e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

}
