
/*-
 * ============LICENSE_START==========================================
 * OPENECOMP - DCAE
 * ===================================================================
 * Copyright (c) 2017 AT&T Intellectual Property. All rights reserved.
 * ===================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0 
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END============================================
 */
	
// Autogenerated
// Do not edit but extend this class as needed
package org.openecomp.dcae.controller.platform.servers.controller;


import org.apache.log4j.Logger;
import org.eclipse.emf.common.util.EList;

import org.openecomp.ncomp.sirius.manager.console.Console;
import org.openecomp.ncomp.sirius.manager.AbstractClient;
import org.openecomp.ncomp.sirius.manager.ManagementServerError;




public class DcaeControllerVirtualMachineServiceConsole extends Console {
	public static final Logger logger = Logger.getLogger(DcaeControllerVirtualMachineServiceConsole.class);
    protected DcaeControllerVirtualMachineServiceClient controller;
    



    public DcaeControllerVirtualMachineServiceConsole(String filename, String name) {
            super(filename, name);
            controller = new DcaeControllerVirtualMachineServiceClient(filename,name);
            client = controller.client;

    }
    
	public DcaeControllerVirtualMachineServiceConsole(AbstractClient c) {
        controller = new DcaeControllerVirtualMachineServiceClient(c);
        client = controller.client;
    }


	public void deploy(String path, java.lang.String instanceName, java.lang.String containerPath) {
		
		try {
			 controller.deploy(path,instanceName,containerPath);
		}
		catch (ManagementServerError e) {
			System.err.println("ERROR: " + e.getJson().toString(2));
		}
		
	}

	public void undeploy(String path, java.lang.String instanceName) {
		
		try {
			 controller.undeploy(path,instanceName);
		}
		catch (ManagementServerError e) {
			System.err.println("ERROR: " + e.getJson().toString(2));
		}
		
	}

	public org.openecomp.dcae.controller.core.service.HealthTestResponse test(String path, java.lang.String instanceName) {
		org.openecomp.dcae.controller.core.service.HealthTestResponse res = null;
		try {
			res =  controller.test(path,instanceName);
		}
		catch (ManagementServerError e) {
			System.err.println("ERROR: " + e.getJson().toString(2));
		}
		return res;
	}

	public void suspend(String path, java.lang.String instanceName) {
		
		try {
			 controller.suspend(path,instanceName);
		}
		catch (ManagementServerError e) {
			System.err.println("ERROR: " + e.getJson().toString(2));
		}
		
	}

	public void resume(String path, java.lang.String instanceName) {
		
		try {
			 controller.resume(path,instanceName);
		}
		catch (ManagementServerError e) {
			System.err.println("ERROR: " + e.getJson().toString(2));
		}
		
	}

	public void pushManagerConfiguration(String path, java.lang.String instanceName) {
		
		try {
			 controller.pushManagerConfiguration(path,instanceName);
		}
		catch (ManagementServerError e) {
			System.err.println("ERROR: " + e.getJson().toString(2));
		}
		
	}

	public void pollManagerConfiguration(String path, java.lang.String instanceName) {
		
		try {
			 controller.pollManagerConfiguration(path,instanceName);
		}
		catch (ManagementServerError e) {
			System.err.println("ERROR: " + e.getJson().toString(2));
		}
		
	}

	public org.eclipse.emf.ecore.EObject managerConfiguration(String path, java.lang.String instanceName) {
		org.eclipse.emf.ecore.EObject res = null;
		try {
			res =  controller.managerConfiguration(path,instanceName);
		}
		catch (ManagementServerError e) {
			System.err.println("ERROR: " + e.getJson().toString(2));
		}
		return res;
	}

	public org.json.JSONObject managerOperation(String path, java.lang.String instanceName, java.lang.String operation, org.json.JSONObject parameters) {
		org.json.JSONObject res = null;
		try {
			res =  controller.managerOperation(path,instanceName,operation,parameters);
		}
		catch (ManagementServerError e) {
			System.err.println("ERROR: " + e.getJson().toString(2));
		}
		return res;
	}

	public void updateConfigurationFromPolicy(String path, java.lang.String instanceName) {
		
		try {
			 controller.updateConfigurationFromPolicy(path,instanceName);
		}
		catch (ManagementServerError e) {
			System.err.println("ERROR: " + e.getJson().toString(2));
		}
		
	}

	public void runHealthTests(String path) {
		
		try {
			 controller.runHealthTests(path);
		}
		catch (ManagementServerError e) {
			System.err.println("ERROR: " + e.getJson().toString(2));
		}
		
	}

	public void updateDeploymentStatus(String path) {
		
		try {
			 controller.updateDeploymentStatus(path);
		}
		catch (ManagementServerError e) {
			System.err.println("ERROR: " + e.getJson().toString(2));
		}
		
	}

}
