
/*-
 * ============LICENSE_START==========================================
 * OPENECOMP - DCAE
 * ===================================================================
 * Copyright (c) 2017 AT&T Intellectual Property. All rights reserved.
 * ===================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0 
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END============================================
 */
	
// Autogenerated
// Do not edit. No need to extend this class.
package org.openecomp.dcae.controller.platform.servers.controller;

import org.openecomp.ncomp.sirius.manager.AbstractClient;
import org.openecomp.ncomp.sirius.manager.HighAvailabilityClient;
import org.openecomp.ncomp.sirius.manager.GenericHttpClient;

import org.apache.log4j.Logger;

import org.openecomp.logger.EcompLogger;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EClass;

import org.openecomp.dcae.controller.platform.controller.impl.DcaePlatformControllerImpl;
import org.openecomp.dcae.controller.platform.controller.ControllerPackage;
import org.openecomp.dcae.controller.platform.servers.controller.logging.DcaePlatformControllerOperationEnum;
import org.openecomp.dcae.controller.platform.servers.controller.logging.DcaePlatformControllerMessageEnum;





 
@SuppressWarnings("unchecked")
public class DcaeDcaePlatformControllerClient extends DcaePlatformControllerImpl {
	public static final Logger logger = Logger.getLogger(DcaeDcaePlatformControllerClient.class);
	static final EcompLogger ecomplogger = EcompLogger.getEcompLogger();
	public AbstractClient client;

	public DcaeDcaePlatformControllerClient(String file, String name) {
		DcaeDcaePlatformController.ecoreSetup(); 
		client = new GenericHttpClient(file,name);
		client.add("/resources", this);
	}

	public DcaeDcaePlatformControllerClient(String file, String name1, String name2) {
		HighAvailabilityClient client1 = new HighAvailabilityClient(file,name1,name2);
		client = client1.all; // requests should be forwarded to all.
		client.add("/resources", this);
	}
	
	public DcaeDcaePlatformControllerClient(AbstractClient c) {
		client = c;
		client.add("/resources", this);
	}



	@Override
	public void deployDescriptor(java.lang.String name) {
		EClass c = ControllerPackage.eINSTANCE.getDcaePlatformController(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(DcaePlatformControllerOperationEnum.REMOTE_deployDescriptor);
		
		try {
		  client.operationPath("/resources", c, "deployDescriptor", null, name);
		}
		catch (Exception e) {
			ecomplogger.warn(DcaePlatformControllerMessageEnum.REMOTE_deployDescriptor, e.toString());
			throw new RuntimeException("remote call failed: " + client.getRemote() + "@deployDescriptor: " + e);
		}
		ecomplogger.recordMetricEventEnd();
		
	}

	@Override
	public void refreshDataBus(java.lang.String nameMatch) {
		EClass c = ControllerPackage.eINSTANCE.getDcaePlatformController(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(DcaePlatformControllerOperationEnum.REMOTE_refreshDataBus);
		
		try {
		  client.operationPath("/resources", c, "refreshDataBus", null, nameMatch);
		}
		catch (Exception e) {
			ecomplogger.warn(DcaePlatformControllerMessageEnum.REMOTE_refreshDataBus, e.toString());
			throw new RuntimeException("remote call failed: " + client.getRemote() + "@refreshDataBus: " + e);
		}
		ecomplogger.recordMetricEventEnd();
		
	}

	@Override
	public void logs(org.json.JSONObject cx, EList<org.openecomp.ncomp.core.logs.LogMessage> logs) {
		EClass c = ControllerPackage.eINSTANCE.getDcaePlatformController(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(DcaePlatformControllerOperationEnum.REMOTE_logs);
		
		try {
		  client.operationPath("/resources", c, "logs", cx != null && cx.has("timeout") ? cx.getLong("timeout") : null, cx,logs);
		}
		catch (Exception e) {
			ecomplogger.warn(DcaePlatformControllerMessageEnum.REMOTE_logs, e.toString());
			throw new RuntimeException("remote call failed: " + client.getRemote() + "@logs: " + e);
		}
		ecomplogger.recordMetricEventEnd();
		
	}

	@Override
	public void metrics(org.json.JSONObject cx, EList<org.openecomp.ncomp.core.metrics.Metric> metrics) {
		EClass c = ControllerPackage.eINSTANCE.getDcaePlatformController(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(DcaePlatformControllerOperationEnum.REMOTE_metrics);
		
		try {
		  client.operationPath("/resources", c, "metrics", cx != null && cx.has("timeout") ? cx.getLong("timeout") : null, cx,metrics);
		}
		catch (Exception e) {
			ecomplogger.warn(DcaePlatformControllerMessageEnum.REMOTE_metrics, e.toString());
			throw new RuntimeException("remote call failed: " + client.getRemote() + "@metrics: " + e);
		}
		ecomplogger.recordMetricEventEnd();
		
	}

	@Override
	public void properties(org.json.JSONObject cx, EList<org.openecomp.ncomp.sirius.manager.properties.AbstractProperty> l) {
		EClass c = ControllerPackage.eINSTANCE.getDcaePlatformController(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(DcaePlatformControllerOperationEnum.REMOTE_properties);
		
		try {
		  client.operationPath("/resources", c, "properties", cx != null && cx.has("timeout") ? cx.getLong("timeout") : null, cx,l);
		}
		catch (Exception e) {
			ecomplogger.warn(DcaePlatformControllerMessageEnum.REMOTE_properties, e.toString());
			throw new RuntimeException("remote call failed: " + client.getRemote() + "@properties: " + e);
		}
		ecomplogger.recordMetricEventEnd();
		
	}

	@Override
	public void uploadInfo(org.json.JSONObject cx, EList<org.openecomp.ncomp.sirius.manager.server.ManagementInfo> info) {
		EClass c = ControllerPackage.eINSTANCE.getDcaePlatformController(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(DcaePlatformControllerOperationEnum.REMOTE_uploadInfo);
		
		try {
		  client.operationPath("/resources", c, "uploadInfo", cx != null && cx.has("timeout") ? cx.getLong("timeout") : null, cx,info);
		}
		catch (Exception e) {
			ecomplogger.warn(DcaePlatformControllerMessageEnum.REMOTE_uploadInfo, e.toString());
			throw new RuntimeException("remote call failed: " + client.getRemote() + "@uploadInfo: " + e);
		}
		ecomplogger.recordMetricEventEnd();
		
	}

	@Override
	public EList<org.openecomp.ncomp.core.metrics.DoubleMetric> getValues(org.json.JSONObject cx, java.lang.String path, java.lang.Long start, java.lang.Long end, org.openecomp.ncomp.core.metrics.MetricValueOption option, boolean relativeInterval) {
		EClass c = ControllerPackage.eINSTANCE.getDcaePlatformController(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(DcaePlatformControllerOperationEnum.REMOTE_getValues);
		EList<org.openecomp.ncomp.core.metrics.DoubleMetric> res;
		try {
		  res = (EList<org.openecomp.ncomp.core.metrics.DoubleMetric>) client.operationPath("/resources", c, "getValues", cx != null && cx.has("timeout") ? cx.getLong("timeout") : null, cx,path,start,end,option,relativeInterval);
		}
		catch (Exception e) {
			ecomplogger.warn(DcaePlatformControllerMessageEnum.REMOTE_getValues, e.toString());
			throw new RuntimeException("remote call failed: " + client.getRemote() + "@getValues: " + e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public EList<org.openecomp.ncomp.core.metrics.DoubleMetric> getValuesAll(org.json.JSONObject cx, java.lang.String path, EList<java.lang.String> metrics, java.lang.Long start, java.lang.Long end, org.openecomp.ncomp.core.metrics.MetricValueOption option, boolean relativeInterval) {
		EClass c = ControllerPackage.eINSTANCE.getDcaePlatformController(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(DcaePlatformControllerOperationEnum.REMOTE_getValuesAll);
		EList<org.openecomp.ncomp.core.metrics.DoubleMetric> res;
		try {
		  res = (EList<org.openecomp.ncomp.core.metrics.DoubleMetric>) client.operationPath("/resources", c, "getValuesAll", cx != null && cx.has("timeout") ? cx.getLong("timeout") : null, cx,path,metrics,start,end,option,relativeInterval);
		}
		catch (Exception e) {
			ecomplogger.warn(DcaePlatformControllerMessageEnum.REMOTE_getValuesAll, e.toString());
			throw new RuntimeException("remote call failed: " + client.getRemote() + "@getValuesAll: " + e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public EList<org.openecomp.ncomp.core.logs.LogMessage> getMessages(org.json.JSONObject cx, java.lang.String path, java.lang.Long start, java.lang.Long end) {
		EClass c = ControllerPackage.eINSTANCE.getDcaePlatformController(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(DcaePlatformControllerOperationEnum.REMOTE_getMessages);
		EList<org.openecomp.ncomp.core.logs.LogMessage> res;
		try {
		  res = (EList<org.openecomp.ncomp.core.logs.LogMessage>) client.operationPath("/resources", c, "getMessages", cx != null && cx.has("timeout") ? cx.getLong("timeout") : null, cx,path,start,end);
		}
		catch (Exception e) {
			ecomplogger.warn(DcaePlatformControllerMessageEnum.REMOTE_getMessages, e.toString());
			throw new RuntimeException("remote call failed: " + client.getRemote() + "@getMessages: " + e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public org.openecomp.ncomp.sirius.manager.server.LoggerInfo getRequestLogger(java.lang.String userName, java.lang.String action, java.lang.String resourcePath, org.json.JSONObject context) {
		EClass c = ControllerPackage.eINSTANCE.getDcaePlatformController(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(DcaePlatformControllerOperationEnum.REMOTE_getRequestLogger);
		org.openecomp.ncomp.sirius.manager.server.LoggerInfo res;
		try {
		  res = (org.openecomp.ncomp.sirius.manager.server.LoggerInfo) client.operationPath("/resources", c, "getRequestLogger", null, userName,action,resourcePath,context);
		}
		catch (Exception e) {
			ecomplogger.warn(DcaePlatformControllerMessageEnum.REMOTE_getRequestLogger, e.toString());
			throw new RuntimeException("remote call failed: " + client.getRemote() + "@getRequestLogger: " + e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public EList<org.openecomp.ncomp.core.function.ValuePair> evaluate(java.lang.String path, org.openecomp.ncomp.core.function.Function function) {
		EClass c = ControllerPackage.eINSTANCE.getDcaePlatformController(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(DcaePlatformControllerOperationEnum.REMOTE_evaluate);
		EList<org.openecomp.ncomp.core.function.ValuePair> res;
		try {
		  res = (EList<org.openecomp.ncomp.core.function.ValuePair>) client.operationPath("/resources", c, "evaluate", null, path,function);
		}
		catch (Exception e) {
			ecomplogger.warn(DcaePlatformControllerMessageEnum.REMOTE_evaluate, e.toString());
			throw new RuntimeException("remote call failed: " + client.getRemote() + "@evaluate: " + e);
		}
		ecomplogger.recordMetricEventEnd();
		return res;
	}

	@Override
	public void update(java.lang.String path, org.openecomp.ncomp.core.function.Function function) {
		EClass c = ControllerPackage.eINSTANCE.getDcaePlatformController(); //foo
		ecomplogger.recordMetricEventStart();
		ecomplogger.setOperation(DcaePlatformControllerOperationEnum.REMOTE_update);
		
		try {
		  client.operationPath("/resources", c, "update", null, path,function);
		}
		catch (Exception e) {
			ecomplogger.warn(DcaePlatformControllerMessageEnum.REMOTE_update, e.toString());
			throw new RuntimeException("remote call failed: " + client.getRemote() + "@update: " + e);
		}
		ecomplogger.recordMetricEventEnd();
		
	}

}
