
/*-
 * ============LICENSE_START==========================================
 * OPENECOMP - DCAE
 * ===================================================================
 * Copyright (c) 2017 AT&T Intellectual Property. All rights reserved.
 * ===================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0 
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END============================================
 */
	
// Autogenerated
// Do not edit. No need to extend this class.
package org.openecomp.dcae.controller.platform.servers.controller;

import org.openecomp.ncomp.sirius.manager.AbstractClient;
import org.openecomp.ncomp.sirius.manager.HighAvailabilityClient;
import org.openecomp.ncomp.sirius.manager.GenericHttpClient;

import org.apache.log4j.Logger;

import org.openecomp.logger.EcompLogger;
import org.openecomp.logger.StatusCodeEnum;
import org.openecomp.logger.EcompException;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EClass;

import org.openecomp.dcae.controller.platform.controller.impl.ControllerClusterImpl;
import org.openecomp.dcae.controller.platform.controller.ControllerPackage;
import org.openecomp.dcae.controller.platform.servers.controller.logging.ControllerClusterOperationEnum;
import org.openecomp.dcae.controller.platform.servers.controller.logging.ControllerClusterMessageEnum;


import org.openecomp.dcae.controller.platform.servers.controller.DcaeDcaePlatformController; 



 
@SuppressWarnings("unchecked")
public class DcaeControllerClusterClient extends ControllerClusterImpl {
	public static final Logger logger = Logger.getLogger(DcaeControllerClusterClient.class);
	static final EcompLogger ecomplogger = EcompLogger.getEcompLogger();
	public AbstractClient client;

	public DcaeControllerClusterClient(String file, String name) {
		DcaeDcaePlatformController.ecoreSetup(); 
		client = new GenericHttpClient(file,name);
		client.add("/cluster", this);
		client.setVersion("ONAP-R2");
	}

	public DcaeControllerClusterClient(String file, String name1, String name2) {
		HighAvailabilityClient client1 = new HighAvailabilityClient(file,name1,name2);
		client = client1.all; // requests should be forwarded to all.
		client.add("/cluster", this);
		client.setVersion("ONAP-R2");
	}
	
	public DcaeControllerClusterClient(AbstractClient c) {
		client = c;
		client.add("/resources", this);
		client.setVersion("ONAP-R2");
	}



	
	public void pushData(String path, java.lang.String serverName, java.lang.String dataName) {
		EClass c = ControllerPackage.eINSTANCE.getControllerCluster(); 
		ecomplogger.recordMetricEventStart(ControllerClusterOperationEnum.ControllerCluster_pushData,client.getRemote());
		
		try {
		  client.operationPath(path, c, "pushData", null, serverName,dataName);
		}
		catch (Exception e) {
			ecomplogger.warn(ControllerClusterMessageEnum.REMOTE_CALL_FAILED_pushData, e.toString());
			EcompException e1 = EcompException.create(ControllerClusterMessageEnum.REMOTE_CALL_FAILED_pushData,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR,ControllerClusterMessageEnum.REMOTE_CALL_FAILED_pushData,e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		
	}

	
	public void receiveData(String path, java.lang.String serverName, java.lang.String dataName, java.util.Date time, java.lang.String content) {
		EClass c = ControllerPackage.eINSTANCE.getControllerCluster(); 
		ecomplogger.recordMetricEventStart(ControllerClusterOperationEnum.ControllerCluster_receiveData,client.getRemote());
		
		try {
		  client.operationPath(path, c, "receiveData", null, serverName,dataName,time,content);
		}
		catch (Exception e) {
			ecomplogger.warn(ControllerClusterMessageEnum.REMOTE_CALL_FAILED_receiveData, e.toString());
			EcompException e1 = EcompException.create(ControllerClusterMessageEnum.REMOTE_CALL_FAILED_receiveData,e,e.getMessage());
			ecomplogger.recordMetricEventEnd(StatusCodeEnum.ERROR,ControllerClusterMessageEnum.REMOTE_CALL_FAILED_receiveData,e.getMessage());
			throw e1;
		}
		ecomplogger.recordMetricEventEnd();
		
	}

}
