
restart: stop start

start:
	M2_HOME=/home/ncomp/.m2 bin/controller-platform-server-controller start
stop:
	bin/controller-platform-server-controller stop
console:
	bin/controller-platform-server-controller console
